### ISSUE TITLE
can't get -f option to work

### ISSUE THREAD

**Issue by colormotor** [codeboost/bea#2]
if I set the -f option to force overwrite I get this error message

error: ENOENT, no such file or directory '/Users/ensta/Documents/work/code/colormotorWorkspace/javascript/beafiles/U'
    at Object.lstatSync (fs.js:420:18)
    at Object.realpathSync (fs.js:878:23)
    at Object.run (/Users/ensta/Documents/work/code/colormotorWorkspace/javascript/bea/src/beaproc.coffee:27:18)
    at Object.<anonymous> (/Users/ensta/Documents/work/code/colormotorWorkspace/javascript/beafiles/bea.coffee:4:4)
    at Object.<anonymous> (/Users/ensta/Documents/work/code/colormotorWorkspace/javascript/beafiles/bea.coffee:6:4)
    at Module._compile (module.js:446:26)
    at Object.run (/usr/local/lib/node_modules/coffee-script/lib/coffee-script/coffee-script.js:79:25)
    at /usr/local/lib/node_modules/coffee-script/lib/coffee-script/command.js:175:29
    at /usr/local/lib/node_modules/coffee-script/lib/coffee-script/command.js:150:18
    at [object Object].<anonymous> (fs.js:123:5)

**Comment by colormotor** [comment]
sorry wrong order of arguments!
